- name: provisioning
  hosts: all
  become: yes
  tasks:
    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-key.asc
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-key.asc] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    - name: Install docker-ce and dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - docker-ce
        update_cache: yes
    - name: Add ansible user to docker group
      user: name=vagrant
            groups=docker
            append=yes
    - name: Install manpages
      apt:
        name:
          - manpages-dev
          - manpages-posix
          - manpages-posix-dev
    - name: Install python related packages
      apt:
        name:
          - python3.10-venv
    - name: create virtualenv
      become: yes
      become_user: vagrant
      shell: python3.10 -m venv venvs/default
      args:
        chdir: /home/vagrant
    - name: Install golang
      apt:
        name:
          - golang
    - name: Install go packages
      become: yes
      become_user: vagrant
      shell: |
        go get -u github.com/monochromegane/the_platinum_searcher/...
        go install github.com/x-motemen/ghq@latest
    - name: Install rust
      apt:
        name:
          - rust-all
    - name: Install misc packages
      apt:
        name:
          - jq
          - pwgen
          - virtualenvwrapper
          - moreutils
          - uniutils
