- name: provisioning
  hosts: all
  become: yes
  tasks:
    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    - name: Install docker-ce and dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - docker-ce
        state: present
        update_cache: yes
    - name: Add ansible user to docker group
      user: name=vagrant
            groups=docker
            append=yes
    - name: Install manpages
      apt:
        name:
          - manpages-dev
          - manpages-posix
          - manpages-posix-dev
    - name: Add deadsnakes ppa
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
    - name: Install python related packages
      apt:
        name:
          - python3.10-venv
    - name: create virtualenv
      become: yes
      become_user: vagrant
      shell: python3.10 -m venv venvs/default
      args:
        chdir: /home/vagrant
    - name: Add longsleep/golang-backports ppa
      ansible.builtin.apt_repository:
        repo: ppa:longsleep/golang-backports
    - name: Install golang
      apt:
        name:
          - golang
    - name: Install misc packages
      apt:
        name:
          - jq
          - pwgen
          - virtualenvwrapper
          - moreutils
          - uniutils
        state: present
        update_cache: yes
